version: "3.3"
services:
  mongodb:
    image: mongo
    expose: 
       - "27017"
    volumes:
      - "mongodata:/data/db"

  back:
    stdin_open: true
    build: 
      context: .
    ports: 
      - "4000:4000"
    volumes:
      - "/app/node_modules"
      - "./:/app"

volumes:
  mongodata: